export * from './opengrid-openconnect-tissue-box'
export {
  OPENGRID_CONFIGURATION,
  OPENGRID_PREVIEW_CONFIGURATION,
  OPENGRID_CONNECTOR_SIDES,
  boundsForOpenGrid,
  cellCenterForOpenGrid,
  isOpenGridGenerationSupported,
  isOpenGridLayeredVariant,
  isOpenGridParameters,
  normalizeOpenGridParameters,
  openGridBoardConfiguration,
  openGridConnectorLocationsFor,
  openGridFileName,
  openGridNominalBoardConfiguration,
  openGridPhysicalBoundsFor,
  openGridScrewCentersFor,
  openGridScrewLatticeDimensions,
  openGridScrewPositionsFor,
  openGridStlFileName,
  screwCenterForOpenGrid,
  validateOpenGridGenerationSupport,
  validateOpenGridParameters,
} from './opengrid'
export {
  boundsForOpenGridOpenShelf,
  isOpenGridOpenShelfParameters,
  openGridOpenShelfAngleRadiansFor,
  openGridOpenShelfCellClearWidthFor,
  openGridOpenShelfClearCellHeightsFor,
  openGridOpenShelfCellSpaceFor,
  openGridOpenShelfDepthFor,
  openGridOpenShelfDividerCentersFor,
  openGridOpenShelfFileName,
  openGridOpenShelfFootprintFor,
  openGridOpenShelfFrontToRearElevationFor,
  openGridOpenShelfPegCentersFor,
  openGridOpenShelfShelfLowerSurfaceZFor,
  openGridOpenShelfShelfCountFor,
  openGridOpenShelfStlFileName,
  openGridOpenShelfTopInnerFrontZFor,
  openGridOpenShelfTopInnerRearZFor,
  openGridOpenShelfTopOuterRearZFor,
  OPENGRID_OPEN_SHELF_CONFIGURATION,
  OPENGRID_OPEN_SHELF_DEFAULT_PARAMETERS,
  validateOpenGridOpenShelfParameters,
} from './opengrid-open-shelf'
export { OPENGRID_OPEN_SHELF_HONEYCOMB_MAX_CELLS } from './opengrid-open-shelf'
export {
  boundsForOpenGridOpenConnectShelf,
  isOpenGridOpenConnectShelfParameters,
  openGridOpenConnectShelfAngleRadiansFor,
  openGridOpenConnectShelfDepthFor,
  openGridOpenConnectShelfFileName,
  openGridOpenConnectShelfFrontHeightFor,
  openGridOpenConnectShelfInstalledBoundsFor,
  openGridOpenConnectShelfMaximumAngleForRows,
  openGridOpenConnectShelfRearHeightFor,
  openGridOpenConnectShelfSlotOriginsFor,
  openGridOpenConnectShelfStlFileName,
  openGridOpenConnectShelfWidthFor,
  OPENGRID_OPENCONNECT_SHELF_CONFIGURATION,
  OPENGRID_OPENCONNECT_SHELF_DEFAULT_PARAMETERS,
  validateOpenGridOpenConnectShelfParameters,
} from './opengrid-openconnect-shelf'
export {
  boundsForOpenGridOpenConnectOrganizer,
  installedBoundsForOpenGridOpenConnectOrganizer,
  isOpenGridOpenConnectOrganizerParameters,
  openGridOpenConnectOrganizerCavityEnvelopeFor,
  openGridOpenConnectOrganizerFileName,
  openGridOpenConnectOrganizerLayoutFor,
  openGridOpenConnectOrganizerPolygonPointsFor,
  openGridOpenConnectOrganizerSlotOriginsFor,
  openGridOpenConnectOrganizerStlFileName,
  openGridOpenConnectOrganizerThreeMfFileName,
  openGridOpenConnectOrganizerTiltAxisFor,
  OPENGRID_OPENCONNECT_ORGANIZER_CONFIGURATION,
  OPENGRID_OPENCONNECT_ORGANIZER_DEFAULT_PARAMETERS,
  OPENGRID_OPENCONNECT_ORGANIZER_SHAPES,
  OPENGRID_OPENCONNECT_ORGANIZER_SPACING_MODES,
  validateOpenGridOpenConnectOrganizerParameters,
} from './opengrid-openconnect-organizer'
export {
  boundsForOpenGridDivider,
  classifyOpenGridDividerShape,
  isOpenGridDividerParameters,
  normalizeOpenGridDividerParameters,
  openGridDividerArmEndpointsFor,
  openGridDividerArmStationsFor,
  openGridDividerAxisFor,
  openGridDividerBaseWidthFor,
  openGridDividerFileName,
  openGridDividerAlignmentInfoFor,
  openGridDividerBoxFitPegCentersFor,
  openGridDividerLatticeStationsFor,
  openGridDividerHoneycombMinHeightFor,
  openGridDividerPegCentersFor,
  openGridDividerPlanBoundsFor,
  openGridDividerPlanDimensionsFor,
  openGridDividerPegLengthFor,
  openGridDividerPegPlanFor,
  openGridDividerRetractionFor,
  openGridDividerStlFileName,
  openGridDividerThreeMfFileName,
  openGridDividerTransitionHeightFor,
  OPENGRID_DIVIDER_CONFIGURATION,
  OPENGRID_DIVIDER_HONEYCOMB_MAX_CELLS,
  validateOpenGridDividerParameters,
} from './opengrid-divider'
export {
  boundsForOpenGridStackableBox,
  externalOpenGridStackableBoxHeightFor,
  openGridStackableBoxActiveFloorTopZFor,
  openGridStackableBoxActiveUpperInnerRimZFor,
  openGridStackableBoxDerivedGeometryFor,
  isOpenGridStackableBoxParameters,
  nominalOpenGridStackableBoxFootprintFor,
  nominalOpenGridStackableBoxBottomGridAxisPositionsFor,
  nominalOpenGridStackableBoxBottomGridCentersFor,
  openGridStackableBoxUpperInnerRimZFor,
  openGridStackableBoxBottomDatumZFor,
  openGridStackableBoxFileName,
  openGridStackableBoxOpeningBottomLengthMaximumFor,
  openGridStackableBoxOrdinaryBottomHoleCentersFor,
  openGridStackableBoxSocketCentersFor,
  openGridStackableBoxStlFileName,
  openGridStackableBoxThreeMfFileName,
  OPENGRID_STACKABLE_BOX_CONFIGURATION,
  OPENGRID_STACKABLE_BOX_DEFAULT_PARAMETERS,
  OPENGRID_STACKABLE_BOX_OPENING_DIRECTIONS,
  OPENGRID_STACKABLE_BOX_OPENING_PARAMETER_KEYS,
  validateOpenGridStackableBoxParameters,
} from './opengrid-stackable-box'
export {
  boundsForOpenGridOrganizerBox,
  isOpenGridOrganizerBoxParameters,
  normalizeOpenGridOrganizerBoxParameters,
  openGridOrganizerBoxCavityEnvelopeFor,
  openGridOrganizerBoxDetachableSocketPosesFor,
  openGridOrganizerBoxFileName,
  openGridOrganizerBoxLayoutFor,
  openGridOrganizerBoxPolygonPointsFor,
  openGridOrganizerBoxStlFileName,
  openGridOrganizerBoxThreeMfFileName,
  OPENGRID_ORGANIZER_BOX_CONFIGURATION,
  OPENGRID_ORGANIZER_BOX_DEFAULT_PARAMETERS,
  validateOpenGridOrganizerBoxParameters,
} from './opengrid-organizer-box'
export {
  boundsForOpenGridStackableCylinder,
  isOpenGridStackableCylinderParameters,
  legacyInnerDiameterFor,
  openGridStackableCylinderDerivedGeometryFor,
  openGridStackableCylinderFileName,
  openGridStackableCylinderHoleCentersFor,
  openGridStackableCylinderOpeningBottomLengthMaximumFor,
  openGridStackableCylinderOuterHoleIndexFor,
  openGridStackableCylinderStlFileName,
  openGridStackableCylinderThreeMfFileName,
  OPENGRID_STACKABLE_CYLINDER_CONFIGURATION,
  OPENGRID_STACKABLE_CYLINDER_DEFAULT_PARAMETERS,
  OPENGRID_STACKABLE_CYLINDER_OPENING_DIRECTIONS,
  OPENGRID_STACKABLE_CYLINDER_OPENING_PARAMETER_KEYS,
  validateOpenGridStackableCylinderParameters,
} from './opengrid-stackable-cylinder'
export {
  boundsForOpenGridSnap,
  isOpenGridSnapParameters,
  isOpenGridSnapFootprint,
  isOpenGridSnapMagnetHoleShape,
  isOpenGridSnapTopText,
  normalizeOpenGridSnapParameters,
  openGridSnapCanonicalAxesFor,
  openGridSnapFileName,
  openGridSnapFootprintForLegacyAxes,
  openGridSnapStlFileName,
  openGridSnapThreeMfFileName,
  OPENGRID_SNAP_CONFIGURATION,
  parseOpenGridSnapDecimalInput,
  validateOpenGridSnapParameters,
} from './opengrid-snap'
export {
  boundsForOpenGridWallCover,
  isOpenGridWallCoverParameters,
  normalizeOpenGridWallCoverText,
  openGridWallCoverFileName,
  openGridWallCoverStlFileName,
  openGridWallCoverThreeMfFileName,
  OPENGRID_WALL_COVER_CONFIGURATION,
  validateOpenGridWallCoverParameters,
} from './opengrid-wall-cover'
export {
  HALF_CELL_CONFIGURATION,
  halfCellDirectionLabel,
  halfCellExtensionFor,
  fullGridCenterOffsetX,
  fullGridCenterOffsetY,
  hasHalfCellX,
  hasHalfCellY,
  halfCellHostPitch,
  isHalfCellX,
  isHalfCellY,
  openGridAxisSize,
  snapFixedCoreAxisSize,
  snapNominalAxisSize,
} from './half-cell'
export { OPENGRID_GRID_CONFIGURATION } from './opengrid-grid'
export {
  OPENGRID_HONEYCOMB_BOTTOM_FEATURE_CLEARANCE,
  OPENGRID_HONEYCOMB_CELL_RADIUS,
  OPENGRID_HONEYCOMB_CONFIGURATION,
  OPENGRID_HONEYCOMB_LOWER_FRAME,
  OPENGRID_HONEYCOMB_RIB_THICKNESS,
} from './opengrid-honeycomb'
export {
  OPENGRID_DETACHABLE_CORNER_SEAT_CONFIGURATION,
  OPENGRID_LEGACY_LOCATING_SEAT_MODE,
  OPENGRID_LOCATING_ASSEMBLY_CONFIGURATION,
  OPENGRID_LOCATING_SEAT_MODES,
  openGridDetachableCornerSeatSocketRotationFor,
  normalizeOpenGridLocatingSeatMode,
} from './opengrid-locating-assembly'
export type { HalfCellDirection, HalfCellX, HalfCellY } from './half-cell'
export type {
  OpenGridSnapBounds,
  OpenGridSnapCanonicalAxes,
  OpenGridSnapFootprint,
  OpenGridSnapMagnetHoleShape,
  OpenGridSnapParameterKey,
  OpenGridSnapParameters,
  OpenGridSnapTopText,
  OpenGridSnapValidation,
  OpenGridSnapValidationIssue,
  OpenGridSnapProfile,
  OpenGridSnapVariant,
} from './opengrid-snap'
export type {
  OpenGridWallCoverParameters,
  OpenGridWallCoverParameterKey,
  OpenGridWallCoverValidation,
} from './opengrid-wall-cover'
export type {
  OpenGridStackableBoxParameterKey,
  OpenGridStackableBoxParameters,
  OpenGridStackableBoxDerivedGeometry,
  OpenGridStackableBoxDerivedOpening,
  OpenGridStackableBoxOpeningDirection,
  OpenGridStackableBoxOpeningParameterKey,
  OpenGridStackableBoxPoint2D,
  OpenGridStackableBoxValidation,
  OpenGridStackableBoxValidationIssue,
} from './opengrid-stackable-box'
export type {
  OpenGridOrganizerBoxBoxMode,
  OpenGridOrganizerBoxCavityEnvelope,
  OpenGridOrganizerBoxCavityEnvelopeInput,
  OpenGridOrganizerBoxDetachableSocketCorner,
  OpenGridOrganizerBoxDetachableSocketPose,
  OpenGridOrganizerBoxLayout,
  OpenGridOrganizerBoxParameterKey,
  OpenGridOrganizerBoxParameters,
  OpenGridOrganizerBoxPoint2D,
  OpenGridOrganizerBoxShape,
  OpenGridOrganizerBoxSpacingMode,
  OpenGridOrganizerBoxStackingLayout,
  OpenGridOrganizerBoxValidation,
  OpenGridOrganizerBoxValidationIssue,
} from './opengrid-organizer-box'
export type {
  OpenGridStackableCylinderDerivedOpening,
  OpenGridStackableCylinderDerivedGeometry,
  OpenGridStackableCylinderOpeningDirection,
  OpenGridStackableCylinderOpeningParameterKey,
  OpenGridStackableCylinderParameterKey,
  OpenGridStackableCylinderParameters,
  OpenGridStackableCylinderProfile,
  OpenGridStackableCylinderPoint2D,
  OpenGridStackableCylinderValidation,
  OpenGridStackableCylinderValidationIssue,
} from './opengrid-stackable-cylinder'
export type {
  OpenGridDetachableCornerSeatPoint2D,
  OpenGridDetachableCornerSeatRotation,
  OpenGridLocatingSeatMode,
} from './opengrid-locating-assembly'
export type {
  OpenGridBoardConfiguration,
  OpenGridChamferMode,
  OpenGridCornerFlags,
  OpenGridConnectorLocation,
  OpenGridConnectorSide,
  OpenGridDirection3D,
  OpenGridFrameSideFlags,
  OpenGridGenerationSupportValidation,
  OpenGridPoint2D,
  OpenGridScrewDimensions,
  OpenGridScrewKind,
  OpenGridScrewMode,
  OpenGridScrewPreset,
  OpenGridScrewPosition,
  OpenGridSideFlags,
  OpenGridTargetFrameShape,
  OpenGridVariant,
  OpenGridValidation,
  OpenGridValidationIssue,
  OpenGridConnectorHoles,
  OpenGridParameters,
  OpenGridParameterKey,
} from './opengrid'
export type {
  OpenGridOpenShelfCellClearHeights,
  OpenGridOpenShelfParameterKey,
  OpenGridOpenShelfParameters,
  OpenGridOpenShelfPoint2D,
  OpenGridOpenShelfValidation,
  OpenGridOpenShelfValidationIssue,
} from './opengrid-open-shelf'
export type {
  OpenGridOpenConnectShelfParameterKey,
  OpenGridOpenConnectShelfParameters,
  OpenGridOpenConnectShelfPoint3D,
  OpenGridOpenConnectShelfValidation,
  OpenGridOpenConnectShelfValidationIssue,
} from './opengrid-openconnect-shelf'
export type {
  OpenGridOpenConnectOrganizerCavityEnvelope,
  OpenGridOpenConnectOrganizerLayout,
  OpenGridOpenConnectOrganizerParameterKey,
  OpenGridOpenConnectOrganizerParameters,
  OpenGridOpenConnectOrganizerPoint2D,
  OpenGridOpenConnectOrganizerPoint3D,
  OpenGridOpenConnectOrganizerShape,
  OpenGridOpenConnectOrganizerSpacingMode,
  OpenGridOpenConnectOrganizerValidation,
  OpenGridOpenConnectOrganizerValidationIssue,
} from './opengrid-openconnect-organizer'
export type {
  OpenGridDividerAlignmentInfo,
  OpenGridDividerAlignmentMode,
  OpenGridDividerAxis,
  OpenGridDividerLatticeAnchor,
  OpenGridDividerPegLengthMode,
  OpenGridDividerPegPlan,
  OpenGridDividerParameterKey,
  OpenGridDividerParameters,
  OpenGridDividerPlanDimensions,
  OpenGridDividerPoint2D,
  OpenGridDividerShape,
  OpenGridDividerValidation,
  OpenGridDividerValidationIssue,
} from './opengrid-divider'
export {
  boundsForPillar,
  isPillarParameters,
  normalizePillarParameters,
  pillarBodyDiameterForParameters,
  pillarFileName,
  pillarLengthForParameters,
  pillarLengthForMode,
  pillarStlFileName,
  PILLAR_CONFIGURATION,
  validatePillarParameters,
} from './opengrid-pillar'
export type {
  PillarBounds,
  PillarDetachableCornerSeatParameters,
  PillarMode,
  PillarParameterKey,
  PillarParameters,
  PillarPositioningParameters,
  PillarValidation,
  PillarValidationIssue,
} from './opengrid-pillar'

export {
  parseDimensionInput,
  parseFiniteDecimalInput,
  parseHalfStepInput,
} from './parse'
export {
  HSW_CELL_CONFIGURATION,
  boundsForHswCell,
  hswCellFileName,
  hswCellOffsetFor,
  hswCellOffsetsForGrid,
  hswCellStlFileName,
  isHswCellParameters,
  validateHswCellParameters,
} from './hsw-cell'
export type {
  HswCellOffset,
  HswCellParameters,
  HswCellValidation,
} from './hsw-cell'
export {
  HEXAGONAL_COLUMN_CONFIGURATION,
  boundsForHexagonalColumn,
  hexagonalColumnFileName,
  hexagonalColumnStlFileName,
  isHexagonalColumnParameters,
  validateHexagonalColumnParameters,
} from './hexagonal-column'
export type {
  HexagonalColumnOrientation,
  HexagonalColumnParameterKey,
  HexagonalColumnParameters,
  HexagonalColumnValidation,
} from './hexagonal-column'
export {
  boundsForBox,
  boxFileName,
  boxStlFileName,
  isBoxParameters,
  validateBoxParameters,
} from './box'
export type {
  BoxBounds,
  BoxParameters,
  BoxValidation,
  DimensionKey,
} from './box'
export {
  boundsForModularGridBase,
  isModularGridBaseParameters,
  modularGridBaseFileName,
  modularGridBaseStlFileName,
  validateModularGridBaseParameters,
} from './modular-grid-base'
export type {
  GridParameterKey,
  ModularGridBaseParameters,
  ModularGridBaseValidation,
} from './modular-grid-base'
export {
  boundsForOpenGridSnapRemover,
  isOpenGridSnapRemoverParameters,
  openGridSnapRemoverFileName,
  openGridSnapRemoverStlFileName,
  validateOpenGridSnapRemoverParameters,
} from './opengrid-snap-remover'
export type {
  OpenGridSnapRemoverParameters,
  OpenGridSnapRemoverValidation,
} from './opengrid-snap-remover'
export { PROTOTYPE_CONFIGURATION } from './prototype-configuration'
export {
  boundsForModel,
  isModelParameters,
  isOpenGridDividerModelParameters,
  isOpenGridModelParameters,
  isOpenGridOpenConnectOrganizerModelParameters,
  isOpenGridLabelCardModelParameters,
  isOpenGridLabelSlotTestModelParameters,
  isOpenGridOpenConnectShelfModelParameters,
  isOpenGridOpenShelfModelParameters,
  isOpenGridOrganizerBoxModelParameters,
  isOpenGridSnapModelParameters,
  isOpenGridStackableBoxModelParameters,
  isOpenGridStackableCylinderModelParameters,
  isOpenGridWallCoverModelParameters,
  isPillarModelParameters,
  modelFileName,
  modelStlFileName,
  validateModelParameters,
} from './model'
export type {
  ModelBounds,
  ModelId,
  ModelParameterKey,
  ModelParameterValues,
  ModelParameters,
  ModelValidation,
  OpenGridDividerModelValidation,
  OpenGridOrganizerBoxModelValidation,
  OpenGridSnapModelValidation,
  OpenGridStackableBoxModelValidation,
  OpenGridStackableCylinderModelValidation,
  OpenGridWallCoverModelValidation,
  PillarModelValidation,
  ScalarModelParameterKey,
  ValidationIssue,
} from './model'

export {
  boundsForOpenGridLabelCard,
  isOpenGridLabelCardParameters,
  isOpenGridLabelCardStyle,
  normalizeOpenGridLabelCardText,
  openGridLabelCardFileName,
  openGridLabelCardStlFileName,
  openGridLabelCardThreeMfFileName,
  OPENGRID_LABEL_CARD_CONFIGURATION,
  OPENGRID_LABEL_CARD_STYLES,
  OPENGRID_LABEL_CARD_ICON_IDS,
  validateOpenGridLabelCardParameters,
} from './opengrid-label-card'

export {
  OPENGRID_LABEL_WIDTH_TIERS,
  OPENGRID_LABEL_CARD_HEIGHT,
  OPENGRID_LABEL_CARD_INSERTION_THICKNESS,
  OPENGRID_LABEL_ACCENT_DEPTH,
  OPENGRID_LABEL_CARD_RAISED_HEIGHT,
  OPENGRID_LABEL_CARD_POCKET_PROUD,
  isOpenGridLabelWidthTier,
  type OpenGridLabelWidthTier,
} from './opengrid-label-shared'
export * from './opengrid-label-slot-test'

export type {
  OpenGridLabelCardParameterKey,
  OpenGridLabelCardParameters,
  OpenGridLabelCardStyle,
  OpenGridLabelCardValidation,
} from './opengrid-label-card'
