const NOMINAL_DIAMETER = 5
const ASSEMBLY_INCREMENT = 0.05
const TEST_SHAFT_DIAMETER = 5
const TEST_FLANGE_DIAMETER = 7
const TEST_SHAFT_EXTERIOR_ALLOWANCE = 1
const INTEGRATED_SEAT_DIAMETER = NOMINAL_DIAMETER
const INTEGRATED_SEAT_HEIGHT = 3
const BOTTOM_EDGE_FILLET_RADIUS = 0.5
const DETACHABLE_SEAT_BODY_DIAMETER = 5
const DETACHABLE_SEAT_SOURCE_BODY_HEIGHT = 3
const DETACHABLE_SEAT_BODY_HEIGHT = 3.8
const DETACHABLE_SEAT_LEAD_IN_HEIGHT = 0.2
const DETACHABLE_SEAT_WEAR_HEIGHT = 0.15
const DETACHABLE_SEAT_SOURCE_TOTAL_HEIGHT = 4.5
const DETACHABLE_SEAT_TOTAL_HEIGHT = 5.3
const DETACHABLE_SEAT_TAPER_TOP_Z = 5.15
const DETACHABLE_SEAT_SOURCE_NOMINAL_VOLUME = 66.7032674
const DETACHABLE_SEAT_NOMINAL_VOLUME = 82.4112179657
const DETACHABLE_LOCK_INDICATOR_WIDTH = 2
const DETACHABLE_LOCK_INDICATOR_RADIAL_LENGTH = 2
const DETACHABLE_LOCK_INDICATOR_DEPTH = 0.15
const DETACHABLE_LOCK_INDICATOR_CUTTER_OVERLAP = 0.01
const DETACHABLE_LOCK_INDICATOR_SOCKET_CLEARANCE = 0.15
const DETACHABLE_LOCK_INDICATOR_LOCK_ROTATION_DEGREES = 90
const DETACHABLE_LOCK_INDICATOR_NOMINAL_REMOVED_VOLUME =
  (DETACHABLE_LOCK_INDICATOR_WIDTH *
    DETACHABLE_LOCK_INDICATOR_RADIAL_LENGTH *
    DETACHABLE_LOCK_INDICATOR_DEPTH) /
  2
const DETACHABLE_HOLDER_SOURCE_DEPTH = 1.5
const DETACHABLE_HOLDER_DEPTH = 1.75
const DETACHABLE_HOLDER_SOURCE_MIN_Z = 3
const DETACHABLE_HOLDER_SOURCE_MAX_Z = 4.5
const DETACHABLE_HOLDER_MAX_Z = 4.75
const DETACHABLE_HOLDER_SOURCE_NOMINAL_VOLUME = 38.4253392
const DETACHABLE_HOLDER_TOP_AREA = 20.94049749435318
const DETACHABLE_HOLDER_EXTENSION_HEIGHT =
  DETACHABLE_HOLDER_DEPTH - DETACHABLE_HOLDER_SOURCE_DEPTH
const DETACHABLE_HOLDER_HOST_OVERLAP = 0.01

export const OPENGRID_LOCATING_SEAT_MODES = [
  'none',
  'hole',
  'integrated',
] as const

export type OpenGridLocatingSeatMode =
  (typeof OPENGRID_LOCATING_SEAT_MODES)[number]

export const OPENGRID_LOCATING_ASSEMBLY_CONFIGURATION = {
  nominalDiameter: NOMINAL_DIAMETER,
  assemblyIncrement: ASSEMBLY_INCREMENT,
  assemblyOpeningDiameter: NOMINAL_DIAMETER + ASSEMBLY_INCREMENT,
  testShaftDiameter: TEST_SHAFT_DIAMETER,
  shaftOpeningDiameter: TEST_SHAFT_DIAMETER,
  testFlangeDiameter: TEST_FLANGE_DIAMETER,
  retainingOpeningDiameter: TEST_FLANGE_DIAMETER + ASSEMBLY_INCREMENT,
  testFlangeHeight: 0.8,
  testShaftExposure: TEST_SHAFT_EXTERIOR_ALLOWANCE,
  integratedSeatDiameter: INTEGRATED_SEAT_DIAMETER,
  integratedSeatHeight: INTEGRATED_SEAT_HEIGHT,
  integratedSeatMinZ: -INTEGRATED_SEAT_HEIGHT,
  bottomEdgeFilletRadius: BOTTOM_EDGE_FILLET_RADIUS,
  testShaftLengthForFloor: (floorThickness: number): number =>
    floorThickness + TEST_SHAFT_EXTERIOR_ALLOWANCE,
} as const

export const OPENGRID_DETACHABLE_CORNER_SEAT_CONFIGURATION = {
  geometryTolerance: 0.02,
  volumeTolerance: 0.02,
  intersectionVolumeTolerance: 1e-6,
  minimumSocketRoof: 0.5,
  male: {
    bodyDiameter: DETACHABLE_SEAT_BODY_DIAMETER,
    bodyHeight: DETACHABLE_SEAT_BODY_HEIGHT,
    leadInHeight: DETACHABLE_SEAT_LEAD_IN_HEIGHT,
    leadInTipDiameter: 4.6,
    keyWidth: 1.8,
    taperTopZ: DETACHABLE_SEAT_TAPER_TOP_Z,
    wearHeight: DETACHABLE_SEAT_WEAR_HEIGHT,
    totalHeight: DETACHABLE_SEAT_TOTAL_HEIGHT,
    nominalVolume: DETACHABLE_SEAT_NOMINAL_VOLUME,
    markedNominalVolume:
      DETACHABLE_SEAT_NOMINAL_VOLUME -
      DETACHABLE_LOCK_INDICATOR_NOMINAL_REMOVED_VOLUME,
    bounds: {
      min: [-2.5, -2.5, 0],
      max: [2.5, 2.5, DETACHABLE_SEAT_TOTAL_HEIGHT],
    },
  },
  maleReference: {
    bodyHeight: DETACHABLE_SEAT_BODY_HEIGHT,
    totalHeight: DETACHABLE_SEAT_TOTAL_HEIGHT,
    nominalVolume: DETACHABLE_SEAT_NOMINAL_VOLUME,
    bounds: {
      min: [-2.5, -2.5, 0],
      max: [2.5, 2.5, DETACHABLE_SEAT_TOTAL_HEIGHT],
    },
  },
  maleSource: {
    bodyHeight: DETACHABLE_SEAT_SOURCE_BODY_HEIGHT,
    totalHeight: DETACHABLE_SEAT_SOURCE_TOTAL_HEIGHT,
    nominalVolume: DETACHABLE_SEAT_SOURCE_NOMINAL_VOLUME,
    bounds: {
      min: [-2.5, -2.5, 0],
      max: [2.5, 2.5, DETACHABLE_SEAT_SOURCE_TOTAL_HEIGHT],
    },
  },
  female: {
    outerDiameter: 7,
    depth: DETACHABLE_HOLDER_DEPTH,
    hostOverlap: DETACHABLE_HOLDER_HOST_OVERLAP,
    passageWidth: 2,
    keySideClearance: 0.1,
    sourceMinZ: DETACHABLE_HOLDER_SOURCE_MIN_Z,
    sourceMaxZ: DETACHABLE_HOLDER_MAX_Z,
    nominalVolume:
      DETACHABLE_HOLDER_SOURCE_NOMINAL_VOLUME +
      DETACHABLE_HOLDER_TOP_AREA * DETACHABLE_HOLDER_EXTENSION_HEIGHT,
    bounds: {
      min: [-3.5, -3.5, DETACHABLE_HOLDER_SOURCE_MIN_Z],
      max: [3.5, 3.5, DETACHABLE_HOLDER_MAX_Z],
    },
  },
  femaleReference: {
    depth: DETACHABLE_HOLDER_SOURCE_DEPTH,
    sourceMinZ: DETACHABLE_HOLDER_SOURCE_MIN_Z,
    sourceMaxZ: DETACHABLE_HOLDER_SOURCE_MAX_Z,
    nominalVolume: DETACHABLE_HOLDER_SOURCE_NOMINAL_VOLUME,
    bounds: {
      min: [-3.5, -3.5, DETACHABLE_HOLDER_SOURCE_MIN_Z],
      max: [3.5, 3.5, DETACHABLE_HOLDER_SOURCE_MAX_Z],
    },
  },
  indicator: {
    width: DETACHABLE_LOCK_INDICATOR_WIDTH,
    radialLength: DETACHABLE_LOCK_INDICATOR_RADIAL_LENGTH,
    depth: DETACHABLE_LOCK_INDICATOR_DEPTH,
    cutterOverlap: DETACHABLE_LOCK_INDICATOR_CUTTER_OVERLAP,
    socketBoundaryClearance: DETACHABLE_LOCK_INDICATOR_SOCKET_CLEARANCE,
    lockRotationDegrees: DETACHABLE_LOCK_INDICATOR_LOCK_ROTATION_DEGREES,
    nominalRemovedVolume: DETACHABLE_LOCK_INDICATOR_NOMINAL_REMOVED_VOLUME,
  },
} as const
